_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
apply_augmentations:
    value: true
apply_batchnorm:
    value: true
apply_maxpool:
    value: true
batch_size:
    value: 128
conv_activation_function:
    value: GELU
dropout_p:
    value: 0.3
feedforward_activation_function:
    value: ReLU
feedforward_dim:
    value: 1024
finetune_strategy:
    value: 0
input_channels:
    value: 3
input_size:
    value: 224
kernel_size:
    value:
        - 7
        - 5
        - 3
        - 3
        - 3
label_smoothing:
    value: 0.2
learning_rate:
    value: 0.0001
max_epoch:
    value: 10
maxpool_kernel_size:
    value: 2
maxpool_padding:
    value: 0
maxpool_stride:
    value: 2
num_channels:
    value:
        - 32
        - 64
        - 128
        - 256
        - 512
num_channels_multiplier:
    value: 1
num_classes:
    value: 10
num_layers:
    value: 5
num_workers:
    value: 16
padding:
    value:
        - 0
        - 0
        - 0
        - 0
        - 0
run_name:
    value: Resnet50_classifier_finetune
seed:
    value: 424
stride:
    value:
        - 1
        - 1
        - 1
        - 1
        - 1
test_data_path:
    value: /speech/shoutrik/Database/INaturalist/inaturalist_12K/test
train_data_path:
    value: /speech/shoutrik/Database/INaturalist/inaturalist_12K/train
valid_data_path:
    value: /speech/shoutrik/Database/INaturalist/inaturalist_12K/valid
wandb_entity:
    value: shoutrik
wandb_project:
    value: ConvNet_expts
warmup_steps:
    value: 250
weight_decay:
    value: 0.0001
